repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.14.1
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: mypy
        args:
          - --show-error-codes
        name: mypy
        entry: poetry run mypy
        require_serial: true
        language: system
        types:
          - python