repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.10
      args: [--config=./pyproject.toml]


- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)

- repo: https://github.com/hadialqattan/pycln
  rev: v1.3.5 # Possible releases: https://github.com/hadialqattan/pycln/tags
  hooks:
    - id: pycln

- repo: "https://github.com/PyCQA/flake8"
  rev: 3.9.2
  hooks:
  - id: flake8
