repos:
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.9
      args: [--config=./pyproject.toml]


- repo: https://github.com/pycqa/isort
  rev: 5.9.2
  hooks:
  - id: isort
    name: isort (python)

- repo: https://github.com/hadialqattan/pycln
  rev: v1.0.3 # Possible releases: https://github.com/hadialqattan/pycln/tags
  hooks:
    - id: pycln

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
