repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9
      args: [--config=./pyproject.toml]


- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
  - id: isort
    name: isort (python)

- repo: https://github.com/hadialqattan/pycln
  rev: v0.0.2 # Possible releases: https://github.com/hadialqattan/pycln/tags
  hooks:
    - id: pycln

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8