apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gitops-cert
spec:
  secretName: gitops-cert-key
  issuerRef:
    name: gitops-issuer
    kind: Issuer
  dnsNames:
  - gitops{{ .Values.domain }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - gitops{{ .Values.domain }}
