apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: gitops-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "info@uptickhq.com"
    privateKeySecretRef:
      name: gitops-issuer-key
    http01: {}
