apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitops-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: gitops
  annotations:
    {{- if .Values.certificate.install }}
    certmanager.k8s.io/cluster-issuer: http-issuer
    {{- end }}
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  - secretName: gitops-cert-key
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: gitops-service
          servicePort: 80
