apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  ACCOUNT_ID: {{ .Values.secrets.ACCOUNT_ID | quote}}
  SLACK_URL: {{ .Values.secrets.SLACK_URL| quote}}
  GITHUB_OAUTH_TOKEN: {{ .Values.secrets.GITHUB_OAUTH_TOKEN| quote}}
  GITHUB_WEBHOOK_KEY: {{ .Values.secrets.GITHUB_WEBHOOK_KEY| quote}}
  SENTRY_DSN: {{ .Values.secrets.SENTRY_DSN| quote}}
data:
  GIT_CRYPT_KEY: {{ .Values.secrets.GIT_CRYPT_KEY | quote}}