apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitops-deployment
  labels:
    app: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
      - name: gitops
        image: 305686791668.dkr.ecr.ap-southeast-2.amazonaws.com/graphtick:latest
        name: web
        ports:
        - containerPort: 8000
      restartPolicy: Always
