name: Lint
on:
  push:
    branches:
      - develop
  pull_request: ~

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install pre-commit
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-3.10-pre-commit-$${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run --all-files

