name: Test
on:
  push:
    branches:
      - develop
  pull_request: ~

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          poetry install -E server
      - name: Run tests...
        run: poetry run py.test
